### ISSUE TITLE
Tag release

### ISSUE THREAD

**Issue by alexreg** [costerwi/rezip#6]
Thanks for this handy utility. Would you kindly be able to tag a release, so I can get this added to macOS Homebrew (or at least my private tap)?

**Comment by costerwi** [comment]
Done. First official release is 1.0.0

**Comment by alexreg** [comment]
Thanks!

**Comment by alexreg** [comment]
For now it can be installed from my Homebrew tap using `brew install alexreg/utilities/rezip`. The project might not have enough stars to get accepted in the core tap, but I can try.

**Comment by costerwi** [comment]
Thanks. Good luck!
